services:
  - type: web
    name: cinemood-app
    env: python
    buildCommand: ""
    startCommand: streamlit run streamlit_app.py --server.port=10000 --server.address=0.0.0.0
    plan: free
